name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: 
      - name: "Group Logging"
        run: |
          echo "::group::my group message"
          echo "Msg1"
          echo "Msg2"
          echo "::endgroup::"
      - name: "Step 1"
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: "Step 2"
        run: |
          echo $MY_VAL
        