name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
      steps: 
        - name: "Group Logging"
          run: |
            echo "::group::my group message"
            echo "Msg1"
            echo "Msg2"
            echo "::endgroup::"
        